### ISSUE TITLE
Problem in using google translate in rtl language

### ISSUE THREAD

**Issue by wssq** [goldendict/goldendict#1056]
Hi
When google translates a word to rtl language, it is shown like picture:
![oie_uqjg6dyemoah](https://user-images.githubusercontent.com/40942247/44772433-13706a80-ab83-11e8-9bac-805ad4b8d5b1.png)

**Comment by darnn** [comment]
Wait, how are you using Google Translate at all? How have you added it?

**Comment by wssq** [comment]
I am using  translate-shell. I act like following link:
https://stackoverflow.com/questions/49972190/how-to-simply-implement-online-dictionaries-for-goldendict/

**Comment by darnn** [comment]
Ahh... I assume you wouldn't know of an easy way to implement this in Windows, right?

**Comment by wssq** [comment]
I use linux (ubuntu).

**Comment by Symbian9** [comment]
Did you sew this Python script for GoldenDict?

- https://github.com/xinebf/google-translate-for-goldendict

**Comment by darnn** [comment]
Not to derail this thread worse than I already did, but I installed that Python script per the instructions on the page, and I get this error in Goldendict:
Query error: The program has returned exit code 1. Traceback (most recent call last): File "D:\gt\googletranslate.py", line 43, in <module> gtrans() File "D:\gt\googletranslate.py", line 37, in gtrans print(result.encode('gbk', 'ignore').decode('gbk')) File "D:\Python\Python37-32\lib\encodings\cp1255.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-34: character maps to <undefined>

**Comment by unprogramable** [comment]
hi you can use

**Comment by Symbian9** [comment]
> `trans -e google -s en -t fa -show-original n -show-original-phonetics n -show-translation y -no-ansi -show-translation-phonetics n -show-prompt-message n -show-languages n -show-original-dictionary n -show-dictionary n -show-alternatives n "%GDWORD%" -no-bidi`

What is that?

BTW, Take a look on this Google Translate Shell-script (bash+curl+sed):

- https://github.com/OPHoperHPO/GT-bash-client
  - How to use it in GoldenDict - https://github.com/OPHoperHPO/GT-bash-client/issues/3

**Comment by unprogramable** [comment]
> > `trans -e google -s en -t fa -show-original n -show-original-phonetics n -show-translation y -no-ansi -show-translation-phonetics n -show-prompt-message n -show-languages n -show-original-dictionary n -show-dictionary n -show-alternatives n "%GDWORD%" -no-bidi`
> 
> What is that?
its translate-shell program you can use it on goldendict just you need change src and dest lang and use it in goldendict .

> BTW, Take a look on this Google Translate Shell-script (bash+curl+sed):
> 
>     * https://github.com/OPHoperHPO/GT-bash-client
>       
>       * How to use it in GoldenDict - [OPHoperHPO/GT-bash-client#3](https://github.com/OPHoperHPO/GT-bash-client/issues/3)

in before i write a program like this in 3 line : both program for me and you have same problem 
when i try to translate multiple line text .program cant translate multiple lines becase of '.' and other symbol .
![translated text](https://i.imgur.com/fpmAK3k.png)
look just tranlate one line ... 
but with translate-shell we can translate multiple lines like this 
![translated text](https://i.imgur.com/XSMdjB2.png)
my old program like its . 
its can multiple line translate but not good like translate shell : 
`#!/usr/bin/env bash
text=$(sed 's/[\W \.]/+/g' <<< "$(xsel -o)"|sed ':a;N;$!ba;s/\n/+\\n+/g')
[[ $(egrep "[A-Za-z]" <<< "$text") ]] && type="fa" || type="en"
translated_text=$(curl -s "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${type}&dt=t&q=${text}"|head -n1|cut -d'"' -f 2|sed 's/\\ n/n/g')
echo "$text > $type > $translated_text"
notify-send -u critical -t 30000 "$(echo -e "$translated_text")"
`

**Comment by Symbian9** [comment]
> its can multiple line translate but not good like translate shell:

Maybe, @OPHoperHPO could help.
