### ISSUE TITLE
After the update to Qt 5.12.3 goldendict crashes on exit

### ISSUE THREAD

**Issue by RedirectCleaner** [goldendict/goldendict#1145]
After the update to Qt 5.12.3, the latest goldendict version crashes when it's closed

```
Thread 1 (Thread 0x7fe7ee425980 (LWP 5033)):
[KCrash Handler]
#6  0x0000000000000021 in ?? ()
#7  0x00007fe80215ea83 in QGestureManager::~QGestureManager (this=0x5621992617a0, __in_chrg=<optimized out>) at kernel/qgesturemanager.cpp:120
#8  0x00007fe80215ed39 in QGestureManager::~QGestureManager (this=0x5621992617a0, __in_chrg=<optimized out>) at kernel/qgesturemanager.cpp:115
#9  0x00007fe7fed4c3ec in QObjectPrivate::deleteChildren() () from /usr/lib64/libQt5Core.so.5
#10 0x00007fe7fed4d1e4 in QObject::~QObject() () from /usr/lib64/libQt5Core.so.5
#11 0x00007fe7fed208ba in QCoreApplication::~QCoreApplication() () from /usr/lib64/libQt5Core.so.5
#12 0x00007fe7ff2cd031 in QGuiApplication::~QGuiApplication() () from /usr/lib64/libQt5Gui.so.5
#13 0x00007fe802114f44 in QApplication::~QApplication() () at kernel/qapplication.cpp:858
#14 0x00005621974cd9f8 in ?? ()
#15 0x00007fe7fe16652b in __libc_start_main (main=0x562197508ee0 <main>, argc=1, argv=0x7ffc7dd68288, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc7dd68278) at ../csu/libc-start.c:308
#16 0x0000562197509dfa in _start ()
```

**Comment by Abs62** [comment]
Try now, should be fixed.

**Comment by RedirectCleaner** [comment]
It works now, thanks for the quick fix.
