### ISSUE TITLE
lrelease error, locale/tr_TR.ts

### ISSUE THREAD

**Issue by nanjigen** [goldendict/goldendict#1338]
Hi, when attempting to build the cloned repo, or installing the `-git` package from the aur, I run into the following error:

```
/usr/bin/lrelease locale/tr_TR.ts -qm locale/tr_TR.qm
lrelease error: Parse error at locale/tr_TR.ts:2591:21: Expected '>' or '/', but got '"'.
make: *** [Makefile:1191: locale/tr_TR.qm] Error 1
```

Possibly related to the latest commit? https://github.com/goldendict/goldendict/commit/4834396a865b60f80a2bc77ddb272941344453e0

**Comment by vedgy** [comment]
The same error is in the CI: https://travis-ci.com/github/Abs62/goldendict/builds/212604290
```
/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease locale/tr_TR.ts -qm locale/tr_TR.qm
/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease locale/qu_WI.ts -qm locale/qu_WI.qm
lrelease error: Parse error at locale/tr_TR.ts:2591:21: Expected '>' or '/', but got '"'.
Makefile:618: recipe for target 'locale/tr_TR.qm' failed
make: *** [locale/tr_TR.qm] Error 1
make: *** Waiting for unfinished jobs....
```
