### ISSUE TITLE
SEGV on indexing EPWING dicts

### ISSUE THREAD

**Issue by MellonQ** [goldendict/goldendict#573]
```
% gdb /usr/bin/goldendict
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/goldendict...Reading symbols from /usr/lib64/debug//usr/bin/goldendict.debug...done.
done.
(gdb) run
Starting program: /usr/bin/goldendict 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Qt: gdb: -nograb added to command-line options.
     Use the -dograb option to enforce grabbing.
[New Thread 0x7fffe1e0f700 (LWP 9835)]
[New Thread 0x7fffe0ae6700 (LWP 9837)]
libpng warning: iCCP: known incorrect sRGB profile
Reloading all the tabs... 
[New Thread 0x7fffd9275700 (LWP 9851)]
DictD: Building the index for dictionary: deutsch_de-ru

Dictd dictionary "/mnt/archive/dict/dictd/deutsch_de-ru.index" reading failed, error: Invalid base64 sequence encountered

Epwing: Building the index for dictionary in directory /mnt/archive/dict/jishou/ja-ru/new/warodai

Skipped too long headword: "     §39. Помета ономат. имеет в словаре расширенное, по сравнению с обычным значением этого слова, применение, а именно: этой пометой выделены все слова, относящиеся к категории так называемых àзвуковых жестов, т.е. выражающие своим звуковым составом образы звуковые, зрительные, осязательные и моторные."
Skipped too long headword: "     б) Русские слова в переводе поговорок и пословиц, которые не входят в собственно буквальный перевод, но необходимы для полного и правильного понимания смысла, например: 思い立つ日が吉日 погов. что задумал, делай не медля (букв. день, когда задумал, и есть счастливый [для дела] день); слова àсчастливый день без того, что вставлено в квадратных скобках, исказили бы смысл поговорки."
Skipped too long headword: "     §26. Гнездование применяется также для некоторых сложных слов, а именно, для таких, которые полностью синонимичны и в словаре по алфавиту оказались рядом. В таком случае вторая часть одного слова дается в скобках как вариант этой второй части, например, вместо двух отдельных полностью синонимичных слов бо:ка-со:ти и бо:ка-сэцуби дается бо:ка-со:ти(-сэцуби) 防火装置(設備).Таким образом написание гайкэй-гугэн(-фуё) 外形具現(賦与) соответствует двум синонимичным словам: гайкэй-гугэн и гайкэй-фуё."
Skipped too long headword: "     §9. Многие слова имеют по нескольку иероглифических написаний, которые и приводятся подряд (ср. §10). При этом запятой разделяются самостоятельные написания, например, сэгарэ 倅, 悴; это означает, что данное слово может встретиться в написании как первым, так и вторым иероглифом."
Skipped too long headword: "     §21. При заимствованных словах до их перевода указывается их происхождение за исключением сложных слов, части которых являются самостоятельными словами и имеются в словаре на соответствующем по алфавиту месте. Например, поскольку в словаре имеются как отдельные слова с указанием их происхождения и айсу и кури:му, то при слове айсукури:му アイスクリーム приводится только перевод. Пометы англ., нем. и т. п. указывают на тот язык, откуда слово непосредственно вошло в японский язык, а не на тот, в кот..."
Skipped too long headword: "     §27. В одну словарную статью соединяются и некоторые морфологические и фонетические варианты слов, а именно, такие, которые идут рядом по алфавиту: а) глаголы в двух формах побудительного залога, т.е. с окончанием су и сэру, например: варавасу 笑わす, варавасэру 笑わせる; б) фонетические варианты, различающиеся краткостью и долготой гласного или одним, в частности конечным гласным, например: айсо, айсо: 愛想; нэкосоги 根刮ぎ, нэкосогэ 根刮げ."
Skipped too long headword: "     §22. Гнездование, т.е. соединение в одной словарной статье нескольких слов, применяется в нескольких случаях. Наиболее частый  включение в одну словарную статью с основным словом производных, образованных от него с помощью следующих формантов: суру (глагольный), на, тэки, сйта (адъективные), ни, дэ, сйтэ (адвербиальные), например:"
Skipped too long headword: "     §10. В тех случаях, когда иероглифическое написание дано не непосредственно после транскрипции, а после цифры, разделяющей значения слов, ставится помета тж. (также) или тк. (только); это означает, что такое написание применяется при употреблении слова не во всех его значениях, а именно в данном, например: àокурэ 後れ 1) (тж. 遅れ) запоздание означает, что в значении àзапоздание окурэ пишется и 後れ и 遅れ. При слове агэру в заглавии указан иероглиф 上げる, а при значении 14-м à(тк. 揚げる) жарить; это о..."
Building a tree of 782 elements
[Thread 0x7fffe0ae6700 (LWP 9837) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd9275700 (LWP 9851)]
0x00007ffff06dd5d4 in free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff06dd5d4 in free () from /lib64/libc.so.6
#1  0x00007ffff6d9debf in eb_finalize_book () from /usr/lib64/libeb.so.13
#2  0x00005555557fa8dc in Epwing::Book::EpwingBook::~EpwingBook (this=0x7fffd9272950, __in_chrg=<optimized out>) at epwing_book.cc:418
#3  0x00005555557f276c in Epwing::makeDictionaries (fileNames=std::vector of length 1, capacity 1 = {...}, indicesDir="/home/gtlinux/.goldendict/index/", 
    initializing=...) at epwing.cc:966
#4  0x000055555574094d in LoadDictionaries::handlePath (this=this@entry=0x7fffffffb0c0, path=...) at loaddictionaries.cc:222
#5  0x000055555573fdfd in LoadDictionaries::handlePath (this=this@entry=0x7fffffffb0c0, path=...) at loaddictionaries.cc:121
#6  0x000055555573fdfd in LoadDictionaries::handlePath (this=this@entry=0x7fffffffb0c0, path=...) at loaddictionaries.cc:121
#7  0x00005555557413eb in LoadDictionaries::run (this=0x7fffffffb0c0) at loaddictionaries.cc:75
#8  0x00007ffff14f1d2c in QThreadPrivate::start (arg=0x7fffffffb0c0)
    at /var/tmp/portage/dev-qt/qtcore-4.8.6-r1/work/qt-everywhere-opensource-src-4.8.6/src/corelib/thread/qthread_unix.cpp:349
#9  0x00007ffff125532d in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff074f9ed in clone () from /lib64/libc.so.6

Also, There is no /mnt/archive/dict/jishou/ja-ru/new/warodai directory, there is /mnt/archive/dict/jishou/ja-ru/new/WARODAI: 
% ls /mnt/archive/dict/jishou/ja-ru/new/ 
CATALOGS  WARODAI  WARODAI.map
```

I guess, there are some troubles in path processing
The dict was fetched from http://warodai.ru/download/warodai_ebwing.zip

**Comment by xiaoyifang** [comment]
too old to verify 
and the zip file is already can not download again.

**Comment by vedgy** [comment]
@MellonQ, if you still experience the bug, please post an up-to-date link to the dictionary and reopen this issue.
